output: assignment4.c circle.o hemisphere.o
	gcc -o output assignment4.c circle.o hemisphere.o -lGL -lglut -lGLU -lX11 -lGLEW -lm

circle.o: circle.c
	gcc -c circle.c

hemisphere.o: hemisphere.c
	gcc -c hemisphere.c
